4 - Django/solutions/mainsite/ajaxdemo/urls.py
from django.conf.urls import url

from . import views

app_name = 'ajaxdemo'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^getdata/$', views.getdata, name='getdata'),
    url(r'^postdata/$', views.postdata, name='postdata')
]

4 - Django/solutions/mainsite/blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.viewposts, name='viewposts'),
    url(r'^viewpost/$', views.viewpost, name='viewpost'),
    url(r'^makepost/$', views.makepost, name='makepost'),
    url(r'^savepost/$', views.savepost, name='savepost'),
    url(r'^savecomment/$', views.savecomment, name='savecomment')
]

4 - Django/solutions/mainsite/mainsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^todo/', include('todo.urls')),
    url(r'^$', include('todo.urls')),
    url(r'^ajaxdemo/', include('ajaxdemo.urls')),
    url(r'^todoajax/', include('todoajax.urls')),
    url(r'^quotes/', include('quotes.urls')),
    url(r'^quotes2/', include('quotes2.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^blog/', include('blog.urls'))
]

4 - Django/solutions/mainsite/ajaxdemo/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
import json

def index(request):
    return render(request, 'ajaxdemo/index.html', {})

def getdata(request):
    data = {'name':'joe', 'age':2324}
    return JsonResponse(data)

def postdata(request):
    data = json.loads(request.body)
    print(data)
    return HttpResponse('OK')

4 - Django/solutions/mainsite/ajaxdemo/templates/ajaxdemo/index.html
<h1>ok</h1>

<script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.1.4/js.cookie.min.js"></script>




<script>

    function http_post(url, data, success) {
        let csrf_token = Cookies.get('csrftoken');
        //let csrf_token = '{% csrf_token %}';
        let xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function() {
            if (this.readyState === 4 && this.status === 200) {
                success(xhttp.responseText);
            }
        };
        xhttp.open("POST", url);
        xhttp.setRequestHeader("Content-Type", "application/json");
        xhttp.setRequestHeader('X-CSRFToken', csrf_token);
        xhttp.send(JSON.stringify(data));
    }


    function http_get(url, success) {
        let xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function() {
            if (this.readyState === 4 && this.status === 200) {
                let data = JSON.parse(xhttp.responseText);
                success(data);
            }
        };
        xhttp.open("GET", url);
        xhttp.send();
    }


    http_get("{% url 'ajaxdemo:getdata' %}", function(data) {
        console.log(data);
    });

    let data = {name:"John Rambo", time:"2pm"};
    http_post("{% url 'ajaxdemo:postdata' %}", data, function(response) {
        console.log(response);
    });

</script>