4 - Django/solutions/mainsite/accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^createuser/$', views.createuser, name='createuser'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^login/$', views.loginpage, name='login'),
    url(r'^loginuser/$', views.loginuser, name='loginuser'),
    url(r'^logout/$', views.logoutuser, name='logout')
]

4 - Django/solutions/mainsite/blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.viewposts, name='viewposts'),
    url(r'^viewpost/$', views.viewpost, name='viewpost'),
    url(r'^makepost/$', views.makepost, name='makepost'),
    url(r'^savepost/$', views.savepost, name='savepost'),
    url(r'^savecomment/$', views.savecomment, name='savecomment')
]

4 - Django/solutions/mainsite/mainsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^todo/', include('todo.urls')),
    url(r'^$', include('todo.urls')),
    url(r'^ajaxdemo/', include('ajaxdemo.urls')),
    url(r'^todoajax/', include('todoajax.urls')),
    url(r'^quotes/', include('quotes.urls')),
    url(r'^quotes2/', include('quotes2.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^blog/', include('blog.urls'))
]

4 - Django/solutions/mainsite/accounts/models.py
from django.db import models

# Create your models here.

4 - Django/solutions/mainsite/accounts/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

def register(request):
    return render(request, 'accounts/register.html')

def createuser(request):

    username = request.POST['username']
    email_address = request.POST['email_address']
    password = request.POST['password']

    if User.objects.filter(username=username).exists():
        return render(request, 'accounts/register.html', {'message':'username already exists'})

    user = User.objects.create_user(username=username, email=email_address, password=password)
    login(request, user)
    return render(request, 'accounts/profile.html')


def loginpage(request):
    return render(request, 'accounts/login.html')

def loginuser(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is None:
        return HttpResponseRedirect(reverse('accounts:login'))
    else:
        login(request, user)
        return HttpResponseRedirect(reverse('accounts:profile'))


# def profile(request):
#     if request.user.is_authenticated:
#         return render(request, 'accounts/profile.html')
#     else:
#         return HttpResponseRedirect(reverse('accounts:register'))


@login_required
def profile(request):
    return render(request, 'accounts/profile.html')


def logoutuser(request):
    logout(request)
    return HttpResponseRedirect(reverse('accounts:login'))

4 - Django/solutions/mainsite/accounts/templates/accounts/login.html
<h1>Login</h1>

<form action="{% url 'accounts:loginuser' %}" method="post" autocomplete="off">
    {% csrf_token %}
    <input type="text" placeholder="username" name="username" required value=""/>
    <input type="password" placeholder="password" name="password" required value=""/>
    <button type="submit">login</button>
</form>

4 - Django/solutions/mainsite/accounts/templates/accounts/profile.html
<h1>Welcome {{request.user.username}}!</h1>

<a href="{% url 'accounts:logout' %}">logout</a>

4 - Django/solutions/mainsite/accounts/templates/accounts/register.html
<h1>Register</h1>

{% if message %}
<span style="color:red">{{message}}</span>
{% endif %}


<form action="{% url 'accounts:createuser' %}" method="post" autocomplete="off">
    {% csrf_token %}
    <input type="text" placeholder="username" name="username" required value=""/>
    <input type="text" placeholder="email address" name="email_address" required value=""/>
    <input type="password" placeholder="password" name="password" required value=""/>
    <button type="submit">register</button>
</form>