4 - Django/solutions/todosite/todoajax/urls.py
from django.conf.urls import url

from . import views

app_name = 'todoajax'
urlpatterns = [
    url(r'^$', views.index, name='gettodos'),
    url(r'^gettodos/$', views.gettodos, name='gettodos'),
    url(r'^savetodo', views.savetodo, name='savetodo')
]

4 - Django/solutions/todosite/todoapp/urls.py
from django.conf.urls import url

from . import views

app_name = 'todoapp'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^addtodo/$', views.addtodo, name='addtodo')
]

4 - Django/solutions/todosite/todosite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^todoapp/', include('todoapp.urls')),
    url(r'^todoajax/', include('todoajax.urls'))
]

4 - Django/solutions/todosite/todoajax/models.py
from django.db import models

from django.db import models

class TodoAjaxItem(models.Model):
    text = models.CharField(max_length=100)

    def __str__(self):
        return self.text

4 - Django/solutions/todosite/todoapp/models.py
from django.db import models

class TodoItem(models.Model):
    text = models.CharField(max_length=100)

    def __str__(self):
        return self.text

4 - Django/solutions/todosite/todoajax/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from .models import TodoAjaxItem
import json

# Create your views here.

def index(request):
    return render(request, 'todoajax/index.html')


def savetodo(request):
    data = json.loads(request.body)
    todo_text = data['todo_text']
    todo_item = TodoAjaxItem(text=todo_text)
    todo_item.save()
    return HttpResponse('ok')


def gettodos(request):
    output = {'todo_items': []}
    todo_items = TodoAjaxItem.objects.all()
    for todo_item in todo_items:
        output['todo_items'].append(todo_item.text)
    return JsonResponse(output)

4 - Django/solutions/todosite/todoapp/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import TodoItem

# Create your views here.

def index(request):
    todo_items = TodoItem.objects.all()
    return render(request, 'todoapp/index.html', {'todo_items': todo_items})

def addtodo(request):
    todo_text = request.POST['todo_text']
    todo_item = TodoItem(text=todo_text)
    todo_item.save()
    return HttpResponseRedirect(reverse('todoapp:index'))

4 - Django/solutions/todosite/todoajax/templates/todoajax/index.html
<script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.1.4/js.cookie.min.js"></script>




<input id="input_todo" type="text">
<button id="bt_add_todo">add todo</button>

<ul id="ul_todo_items">
</ul>

<script>


    function http_post(url, data, success) {
        let csrf_token = Cookies.get('csrftoken');
        let xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function() {
            if (this.readyState === 4 && this.status === 200) {
                success(xhttp.responseText);
            }
        };
        xhttp.open("POST", url);
        xhttp.setRequestHeader("Content-Type", "application/json");
        xhttp.setRequestHeader('X-CSRFToken', csrf_token);
        xhttp.send(JSON.stringify(data));
    }


    function http_get(url, success) {
        let xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function() {
            if (this.readyState === 4 && this.status === 200) {
                let data = JSON.parse(xhttp.responseText);
                success(data);
            }
        };
        xhttp.open("GET", url);
        xhttp.send();
    }

    let ul_todo_items = document.querySelector('#ul_todo_items');
    let input_todo = document.querySelector('#input_todo');
    let bt_add_todo = document.querySelector('#bt_add_todo');


    function refresh_list() {
        http_get("{% url 'todoajax:gettodos' %}", function(data) {
            while (ul_todo_items.firstChild) {
                ul_todo_items.removeChild(ul_todo_items.firstChild);
            }
            for (let i=0; i<data.todo_items.length; ++i) {
                let li = document.createElement('li');
                li.innerText = data.todo_items[i];
                ul_todo_items.appendChild(li);
            }
        });
    }


    bt_add_todo.onclick = function() {
        let todo_text = input_todo.value;
        let data = {
            todo_text: todo_text
        };
        http_post("{% url 'todoajax:savetodo' %}", data, function(response) {
            // if (response === 'ok') {
            //     let li = document.createElement('li');
            //     li.innerText = todo_text;
            //     ul_todo_items.appendChild(li);
            // }
            refresh_list();
        });
    };

    refresh_list();




</script>

4 - Django/solutions/todosite/todoapp/templates/todoapp/index.html
<form action="{% url 'todoapp:addtodo' %}" method="post">
    {% csrf_token %}
    <input type="text" name="todo_text">
    <button type="submit">add todo</button>
</form>


<ul>
    {% for todo_item in todo_items %}
    <li>{{todo_item.text}}</li>
    {% endfor %}
</ul>